stack:	stack.cpp
	g++ -g stack.cpp -o stack
clean_stack:
	rm stack 


queue:	Queue.cpp
	g++ -g Queue.cpp -o Queue
clean_queue:
	rm Queue 


linkqueue:	linkqueue.cpp
	g++ -g linkqueue.cpp -o linkqueue
clean_linkqueue:
	rm linkqueue
