Bubble:
	g++ -g Bubble.cpp  -o Bubble
SelectSort:
	g++ -g SelectSort.cpp -o SelectSort 
InsertSort:
	g++ -g InsertSort.cpp -o InsertSort 
HeapSort:
	g++ -g HeapSort.cpp -o HeapSort 


clean_Bubble:
	rm Bubble
clean_Select:
	rm SelectSort
clean_Insert:
	rm InsertSort
clean_Heap:
	rm HeapSort
