Bubble:
	g++ -g Bubble.cpp  -o Bubble
SelectSort:
	g++ -g SelectSort.cpp -o SelectSort 
InsertSort:
	g++ -g InsertSort.cpp -o InsertSort 


clean_Bubble:
	rm Bubble
clean_Select:
	rm SelectSort
clean_Insert:
	rm InsertSort
