Sequential_Search:	
	gcc -g Sequential_Search.cpp -o Sequential_Search
Binary_Search:
	gcc -g Binary_Search.cpp -o Binary_Search
Fibonacci_Search:
	gcc -g Fibonacci_Search.cpp -o Fibonacci_Search

clean_Sequential:
	rm Sequential_Search
clean_Binary:
	rm Binary_Search
clean_Fibonacci:
	rm Fibonacci_Search
