Sequential_Search:	
	g++ -g Sequential_Search.cpp -o Sequential_Search
Binary_Search:
	g++ -g Binary_Search.cpp -o Binary_Search
Fibonacci_Search:
	g++ -g Fibonacci_Search.cpp -o Fibonacci_Search
BTree_Search:
	g++ -g BTree_Search.cpp -o BTree_Search

clean_Sequential:
	rm Sequential_Search
clean_Binary:
	rm Binary_Search
clean_Fibonacci:
	rm Fibonacci_Search
clean_BTree:
	rm BTree_Search
